export const products = [
    {
        id: 1,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588711/Bit%203D/llavero3_kyesvg.png',
        title: 'Llavero Rana',
        description: 'Llavero con diseño a ranas',
        price: 150.0,
        stock: 10,
        categoryId: 'llaveros',
        cartCount: 0,
    },
    {
        id: 2,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588711/Bit%203D/llavero1_qpzxvx.png',
        title: 'Llavero Dinosaurio',
        description: 'Llavero blanco con diseño a dinosaurio',
        price: 250.0,
        stock: 20,
        categoryId: 'llaveros',
        cartCount: 0,
    },
    {
        id: 3,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588712/Bit%203D/llavero4_vr1lxc.png',
        title: 'Llavero Nene',
        description: 'Llavero con diseño a un nene',
        stock: 20,
        price: 100.0,
        categoryId: 'llaveros',
        cartCount: 0,
    },
    {
        id: 4,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588712/Bit%203D/llavero2_adijmx.png',
        title: 'LLaveros Varios',
        description: 'LLaveritos con diseños variados',
        stock: 50,
        price: 100.0,
        categoryId: 'llaveros',
        cartCount: 0,
    },
    {
        id: 5,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588714/Bit%203D/mu%C3%B1eco4_wc20ng.png',
        title: 'Muñecos Chibis Personalizados',
        description: 'Muñecos Chibi Personalizables',
        stock: 5,
        price: 300.0,
        categoryId: 'muniecos',
        cartCount: 0,
    },
    {
        id: 6,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588714/Bit%203D/mu%C3%B1eco2_n3vwlx.png',
        title: 'Muñeco Chibi Capitan America',
        description: 'Muñeco Chibi Capitan America, para coleccion',
        stock: 10,
        price: 500.0,
        categoryId: 'muniecos',
        cartCount: 0,
    },
    {
        id: 7,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588714/Bit%203D/mu%C3%B1eco3_ghcbac.png',
        title: 'Muñeco Naruto',
        description: 'Muñeco Naruto Shipodden personalizable',
        stock: 5,
        price: 500.0,
        categoryId: 'muniecos',
        cartCount: 0,
    },
    {
        id: 8,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588713/Bit%203D/mu%C3%B1eco1_wf8lnv.png',
        title: 'Muñeco Chibi Thor',
        description: 'Muñeco Chibi Thor, para coleccion',
        stock: 20,
        price: 500.0,
        categoryId: 'muniecos',
        cartCount: 0,
    },
    {
        id: 9,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588713/Bit%203D/maceta3_fdatti.png',
        title: 'Macena La Ferina',
        description: 'Maceta Modelo La Ferina para decorar tu casa',
        stock: 10,
        price: 800.0,
        categoryId: 'macetas',
        cartCount: 0,
    },
    {
        id: 10,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588712/Bit%203D/maceta1_h8a29y.png',
        title: 'Maceta Deco Perrito',
        description: 'Maceta Deco perrito para decorar tu casa',
        stock: 5,
        price: 700.0,
        categoryId: 'macetas',
        cartCount: 0,
    },
    {
        id: 11,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588712/Bit%203D/maceta2_oahpts.png',
        title: 'Maceta Deco Perrito',
        description: 'Maceta Deco perrito para decorar tu casa',
        stock: 15,
        price: 700.0,
        categoryId: 'macetas',
        cartCount: 0,
    },
    {
        id: 12,
        img: 'https://res.cloudinary.com/dzrb2apcj/image/upload/v1637588713/Bit%203D/maceta4_lh0yew.png',
        title: 'Maceta Buda',
        description: 'Maceta Buda, para decorar tu casa',
        stock: 10,
        price: 1500.0,
        categoryId: 'macetas',
        cartCount: 0,
    },
]